addons:
  ssh_known_hosts: aqua.aquatan.studio
script:
- echo ok
before_install:
- openssl aes-256-cbc -K $encrypted_e0de04b896a6_key -iv $encrypted_e0de04b896a6_iv -in .travis/deploy_key.enc -out /tmp/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key
deploy:
  provider: script
  skip_cleanup: true
  script: /bin/bash .travis/deploy.sh
  on:
    branch: master
