sudo: false
dist: xenial
language: node
node_js:
  - 10

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

script:
  - make lint
